site_name: AI Notes
site_url: https://rokmr.github.io/notes/
site_author: Rohit Kumar
site_description: Notes for Artificial Intelligence

repo_name: rokmr/notes
repo_url: https://github.com/rokmr/notes

copyright: Copyright &copy; 2025 Rohit Kumar

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.expand
    # - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  icon:
    logo: material/book-open
    navigation:
      Home: material/home
      Basic: material/book-open-page-variant
      Machine Learning: material/robot
      Computer Vision: material/camera
      Natural Language Processing: material/text-recognition
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right


  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: lime
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: custom
      accent: lime

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - social
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - glightbox
  - mkdocs-video
  - mkdocs-jupyter:
      include: ["*.ipynb"]  # Process all notebook files
  - minify:
      minify_html: true
  - macros

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rokmr
    - icon: fontawesome/solid/envelope
      link: mailto:sahil15rohit88@gmail.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rohitronie/
    - icon: fontawesome/solid/globe
      link: https://rokmr.github.io


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - tables
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - def_list
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true


nav:
  - Home: 
    - Home: index.md

  - Basic: 
    - Basic: basics/index.md
    - Probability: basics/Probability.md
    - Vector Calculus: basics/VectorCalculus.md
    - Distance: basics/Distance.md
    - Information Theory: basics/InfoTheory.md
    - Bias & Variance: basics/BiasVar.md
    - Activation: basics/Activation.md
    - Loss: basics/Loss.md
    - Optimization: basics/Optimization.md
    - Scheduler: basics/Scheduler.md
    - Regularization: basics/Regularization.md
    - Attention: basics/Attention.md
    - Position Encoding: basics/PositionEncoding.md
    - Metric: basics/Metric.md
    - Inference: basics/Inference.md
    - Extra: basics/Extra.md

  - Machine Learning: 
    - Machine Learning: ml/index.md
    - Linear Regression: ml/LinearRegression.md
    - Logistic Regression: ml/LogisticRegression.md
    - Naive Bayes: ml/NaiveBayes.md
    - Dimensionality Reduction:
      - Dimensionality Reduction: ml/dimReduction/index.md
      - PCA: ml/dimReduction/PCA.md
      - LDA: ml/dimReduction/LDA.md
    - k-NN: ml/KNN.md
    - Clustering:
      - Clustering: ml/clustering/index.md
      - k-Means: ml/clustering/KMeans.md
      - DBSCAN: ml/clustering/DBSCAN.md
      - HDBSCAN: ml/clustering/HDBSCAN.md
      - Hierarchical Clustering: ml/clustering/HierarchicalClustering.md
      - GMM: ml/clustering/GMM.md
    - SVM: ml/SVM.md



  - Computer Vision: 
    - Computer Vision: cv/index.md

    - CNN: 
      - CNN: cv/cnn/index.md

    - Object Detection: 
      - Object Detection: cv/detection/index.md
      - Selective Search: cv/detection/SelectiveSearch.md
      - Overfeat: cv/detection/Overfeat.md 
      - RCNNs: cv/detection/RCNN.md
      - YOLO: cv/detection/YOLO.md
      - RetinaNet: cv/detection/RetinaNet.md
      - CornerNet: cv/detection/CornerNet.md
      - CenterNet: cv/detection/CenterNet.md
      - ExtremeNet: cv/detection/ExtremeNet.md
      - DETR: cv/detection/DETR.md
      - YOLO-World: cv/detection/YOLO-World.md

    - Face Detection: 
      - Face Detection: cv/faceDetection/index.md

    - Pose Estimation:
      - Pose Estimation: cv/poseEstimation/index.md

    - Image Segmentation:
      - Image Segmentatio: cv/segmentation/index.md
      - DIS: cv/segmentation/DIS.md
      - BiRefNet: cv/segmentation/BiRefNet.md 

    - Optical Flow: 
      - Optical Flow: cv/opticalFlow/index.md

    - Object Tracking:
      - Object Tracking: cv/objectTracking/index.md 

    - NeRF:
      - NeRF: cv/nerf/index.md


  - Natural Language Processing:
    - Natural Language Processing: nlp/index.md
